henriits/Socialmediaproject1

- kat.txt
Adding new text file for testing, test file name is kat.txt
> add new file kat.txt

- what_if.py
Adding new python file what_if.py
> add new file what_if.py

- todays_test.txt
Want to be sure I remember yesterday practice :)
> add todays_test.txt file

- static/css/styles.css
- templates/base.html
- templates/home.html
added login / logout links, connected them , added button to redirect to top on click , changed names for now
> created new branch, old one gone messy

- static/css/styles.css
- templates/base.html
- templates/home.html
> Changed Landingpage design

- socialmedia/models.py
- users/forms.py
- users/templates/users/old_register.html
- users/templates/users/register.html
But it has an issue with red text overlaps with grey one if you enter incorrect credentials
> Register with crispy form

- static/css/register.css
- static/css/styles.css
- users/forms.py
- users/templates/users/register.html
> added def __init__ to userregistrationform

- posts/urls.py
- socialmedia/urls.py
- static/css/styles.css
- templates/feed/posts.html
Added like and comment field to post feed, but it is not working.
> Added like and comment field to post feed

- posts/urls.py
- posts/views.py
- templates/base.html
- templates/feed/posts.html
currently searchbar works, but it looks for post title/ text , needs to be fixed in future so it looks for users instead
> Added searchbar

- static/css/edit_profile.css
- users/forms.py
- users/templates/users/edit_profile.html
- users/templates/users/profile.html
- In edit_profile picture is now has a default size + square
- 'Edit profile' button on Profile page now redirects to 'edit profile' page 
- Fixed appearance of 'Edit profile' page: 
- - deleted unnecessary fields (location remains since we will use it in future)
- - date of birth + username are not editable fields
> Profile, edit profile - small changes and bug fixes 

- socialmedia/urls.py
- templates/base.html
- users/templates/users/profile.html
- users/templates/users/search.html
- users/urls.py
- Moved profile and edit_profile urls from socialmedia app to users app 
- Changed mentioned urls in html files by adding referral to 'users'
> Moved profile and edit profile to Users app 

- posts/views.py
- static/css/styles.css
- templates/feed/posts.html
Changed image upload and post upload buttons and functionality. At the moment it is not working, new post is not uploaded. Also changed posts image height in css file.
> Create post field: upload image button and upload post button

- README.md
- posts/urls.py
- posts/views.py
- templates/base.html
- templates/feed/posts.html
posts are now able to be posted from posts.html, createpost url not required ( removed )
> Testbranch1

- posts/views.py
Like and remove like function is working.
> Like and remove like function added.

- posts/forms.py
- posts/views.py
- static/css/feedpage.css
- static/css/landingpage.css
- static/css/messages.css
- static/css/styles.css
- templates/base.html
- templates/feed/post_delete.html
- templates/feed/posts.html
- templates/feed/update_post.html
- templates/messages/create_thread.html
- templates/messages/inbox.html
- templates/sidebar.html
- users/templates/users/search.html
- changed the style of the posts page, and layout, refactord css files into seperate files
> Refactoring css1

- notifications/templates/show_notifications.html
- posts/views.py
- templates/base.html
changed notifications view, and post views, now users get notification when
1.  someone creates a new post, 
2.  comments on user post, 
3.  likes user post!
> Notifications4

- notifications/templates/show_notifications.html
- static/css/stickyside.css
- templates/feed/posts.html
- templates/messages/inbox.html
- templates/sidebar.html
- templates/weatherapi.html
- users/templates/users/newusers.html
- users/templates/users/search.html
made right side boxes on search and post page sticky, edited the looks of all buttons and links
> Stickyboxes

- static/css/posts.css
- templates/feed/posts.html
Post images are centered, no more stretching, and smaller (max height 1000px for now. Can adjust it if needed)
> post images are smaller, not strethced, and now centered

- notifications/templates/show_notifications.html
- static/css/notifications.css
- static/js/notifications.js
changed notification display, connected to detail view of the post, added X to close notification, but does not completely delete it yet, need to connect it to DB
> Testdrive1

- posts/views.py
Solved
If not logged in trying to access /posts/ -> redirects to login -> then after login it redirects to posts
> if user not logged in - redirect him to login page

- templates/feed/posts.html
> fixed the img size appearance

- static/js/like_counter_no_scroll_script.js
- static/js/scripts.js
- templates/feed/posts.html
Now counter is attached only to the specific post:
If you leave a like under the post, counter will be changes only for this specific post 
Also moved the script to a separate js file - script.js
> Fix like counter

- templates/home.html
> landing page text update

- posts/views.py
> fixed like notifications
